### ISSUE TITLE
Gmail connection is not working

### ISSUE THREAD

**Issue by ahilles107** [hcengineering/huly-selfhost#4]
Error:
```
gmail.acef719de9c53e6257e7.js:1 
        
        
GET http://xxx.xxx.xxx:8088/signin?redirectURL=http%3A%2F%2Fxxx.xxx.xxx%2Fworkbench%2Fmikolajczuk%2Fsetting%2Fintegrations net::ERR_CONNECTION_REFUSED
s @ gmail.acef719de9c53e6257e7.js:1
(anonymous) @ bundle.93d3c932611b373f368a.js:217
Yo @ bundle.93d3c932611b373f368a.js:217
bn @ bundle.93d3c932611b373f368a.js:198
gmail.acef719de9c53e6257e7.js:1 
        
        
   Uncaught (in promise) TypeError: Failed to fetch
at HTMLButtonElement.s (gmail.acef719de9c53e6257e7.js:1:85822)
at bundle.93d3c932611b373f368a.js:217:2437
at Array.forEach (<anonymous>)
at HTMLButtonElement.Yo (bundle.93d3c932611b373f368a.js:217:2422)
at HTMLButtonElement.bn (bundle.93d3c932611b373f368a.js:198:14956)```

Looks like the app tried to connect to a service behind `8088` port. I don't see any service with this port configured in docker-compose. Something is missing?

**Comment by Aswin2667** [comment]
> Error:
> 
> ```
> gmail.acef719de9c53e6257e7.js:1 
>         
>         
> GET http://xxx.xxx.xxx:8088/signin?redirectURL=http%3A%2F%2Fxxx.xxx.xxx%2Fworkbench%2Fmikolajczuk%2Fsetting%2Fintegrations net::ERR_CONNECTION_REFUSED
> s @ gmail.acef719de9c53e6257e7.js:1
> (anonymous) @ bundle.93d3c932611b373f368a.js:217
> Yo @ bundle.93d3c932611b373f368a.js:217
> bn @ bundle.93d3c932611b373f368a.js:198
> gmail.acef719de9c53e6257e7.js:1 
>         
>         
>    Uncaught (in promise) TypeError: Failed to fetch
> at HTMLButtonElement.s (gmail.acef719de9c53e6257e7.js:1:85822)
> at bundle.93d3c932611b373f368a.js:217:2437
> at Array.forEach (<anonymous>)
> at HTMLButtonElement.Yo (bundle.93d3c932611b373f368a.js:217:2422)
> at HTMLButtonElement.bn (bundle.93d3c932611b373f368a.js:198:14956)```
> 
> Looks like the app tried to connect to a service behind `8088` port. I don't see any service with this port configured in docker-compose. Something is missing? 
> ```

did you find any solution for this issue?
