### ISSUE TITLE
Traefik Deployment not working

### ISSUE THREAD

**Issue by sagarsubedi** [hcengineering/huly-selfhost#69]
I bought a server from hetzner, added firewall for 80, 443, and 22. Then followed the steps for the traefik deployment, but I am getting this error. Any help would be appreciated. Again, I did not do the nginx stuff at all. Directly followed the traefik instructions only. I was able to sign up, and got logged in, but then I see this in the "dashboard" page and nothing else other than the header.

SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS. -- Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:7298
    at https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:7385
    at qf.withSync (https://MY_DOMAIN/bundle.ebb4769acdad72460151.js:9367:63146)
    at E.openConnection (https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:7353)
    at E.scheduleOpen (https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:4436)
    at new Connection (https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:3042)
    at connect (https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:11225)
    at https://MY_DOMAIN/5360.f687a8d2a381ee249500.js:1:12729
    at https://MY_DOMAIN/bundle.ebb4769acdad72460151.js:9367:33208
    at qf.with (https://MY_DOMAIN/bundle.ebb4769acdad72460151.js:9367:62953)

**Comment by aonnikov** [comment]
@sagarsubedi thanks for reporting this. There was a typo in the traefik configuration template.
